# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4740d3c96962aa6b6f15eee679963265c991685f651700e5023ad5abb75d9176cb632a7ca0bffe74c15e68b0d297c934d2b5299ad28e64e54595e9e5f5b4b24e

test:
  secret_key_base: a77f541d53f2939692410d43fac6a70704ea94cebe553ab996b0552518f24aab6c6118eeded001b0e2e931b6aa1b58ca60b2b0dc57f9e26874001ae7ed8a976f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
